name: Render CV.pdf, then trigger GHA on personal_website_distill

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install dependencies
        run: Rscript -e 'install.packages(c("rmarkdown"))'

      - name: Render CV
        run: Rscript -e 'rmarkdown::render("cv.Rmd")'
        
      - name: Trigger website rendering
        if: success()
        run: |
         curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/etiennebacher/personal_website_distill/dispatches --data '{"event_type": "build_application"}'