name: Trigger GHA on personal_website_distill

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger website rendering
        run: |
         curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/etiennebacher/personal_website_distill/dispatches --data '{"event_type": "Trigger from CV_perso"}'
