name: Trigger GHA on personal_website_distill

on:
  push:

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger website rendering
        run: |
         curl -X POST \
         -H "Authorization: Bearer ${{secrets.ACCESS_TOKEN}}" \
         -H "Accept: application/vnd.github.v3+json" \
         https://api.github.com/repos/etiennebacher/personal_website_distill/actions/workflows/main.yml/dispatches \
         -d '{"ref": "master"}'